site_name: Documentation Service 
site_description: Documentation With Matter


nav:
- Documentation:
  - about AItool: 'src/AItool.md'
- D-Link Device for matter:
    - Version1.1: 'src/matter1.1.md'
- Test:
    -test: 'src/TEST.md'

 
  
plugins:
  - exclude:
      regex:
        - '.*(^|\/)snippets\/.*$'
      glob:
        - src/sites/*
