site_name: My Documentation
site_description: Documentation Templane

theme:
  name: material
  language: zh-TW
  
docs_dir: docs

nav:
  - 首頁: index.md
  - Extensions:
      - Includes: extensions/includes/index.md
      - Material: extensions/material/index.md
      - Mermaid: extensions/mermaid/index.md

markdown_extensions:
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - admonition
  - codehilite
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css